#!/bin/bash

CODE_DIR=$SRC_DIR"/mlt"

REPOLOC="git://github.com/mltframework/mlt.git"
REVISION="e8325f5e9acce9c41b3e91d7b587a41c91b8d0d7" # 6.4.1

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

git clone $REPOLOC
cd $CODE_DIR
git checkout $REVISION

cd $CODE_DIR

export CFLAGS="-I$INCLUDE_DIR"
export LDFLAGS="-L$LIB_DIR"

./configure --prefix=$FINAL_INSTALL_DIR --libdir=$FINAL_INSTALL_DIR --enable-gpl --enable-linsys --swig-languages=python
make
make install
