#!/bin/bash

function build_ffmpeg() {
	cd $DIR

	CODE_DIR=$SRC_DIR"/FFmpeg"

	REPOLOC="git://github.com/FFmpeg/FFmpeg.git"
	REVISION="HEAD"

	if [ -d "$CODE_DIR" ]; then
	  echo "Deleting dir "$CODE_DIR
	  rm -rf $CODE_DIR 
	  mkdir $CODE_DIR
	fi

	cd $SRC_DIR

	git clone $REPOLOC
	cd $CODE_DIR
	git checkout $REVISION

	cd $CODE_DIR

	CFLAGS="-I$INCLUDE_DIR"
	LDFLAGS="-L$LIB_DIR"

	./configure --prefix=$FINAL_INSTALL_DIR --libdir=$FINAL_INSTALL_DIR  --disable-doc --disable-network --disable-ffserver --enable-gpl --enable-version3 --enable-shared --enable-debug --enable-pthreads --enable-runtime-cpudetect --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libvpx
	make
	make install
}

# Make sure were in script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_DIR=$DIR
SRC_DIR=$SCRIPT_DIR"/src"

USR_LIB_DIR="/usr/lib/x86_64-linux-gnu"
FINAL_INSTALL_DIR=$USR_LIB_DIR
INCLUDE_DIR=$FINAL_INSTALL_DIR"/include"
LIB_DIR=$FINAL_INSTALL_DIR

export CFLAGS=
export CXXFLAGS=
export LDFLAGS=

case "$1" in
	"ffmpeg")
		build_ffmpeg
		;;
	"setup")
		setup
		;;
	*)
		echo "Unknown command: $1"
		;;
esac
