#!/bin/bash

CODE_DIR=$SRC_DIR"/x264"

REPOLOC="git://repo.or.cz/x264.git"
REVISION="HEAD"

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

git clone $REPOLOC
cd $CODE_DIR
git checkout $REVISION

FINAL_LIB_DIR=$FINAL_INSTALL_DIR"/x64-10bit"

export CFLAGS="-I$INCLUDE_DIR"
export LDFLAGS="-L$FINAL_LIB_DIR"


./configure --prefix=$FINAL_INSTALL_DIR --libdir=$FINAL_LIB_DIR  --disable-lavf --disable-ffms --disable-gpac --disable-swscale --enable-shared
make
make install
