#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SRC_DIR=$SCRIPT_DIR"/src"
CODE_DIR=$SRC_DIR"/mlt"

LIB_DIR="/usr/lib/x86_64-linux-gnu"

REPOLOC="git://github.com/mltframework/mlt.git"
REVISION="e8325f5e9acce9c41b3e91d7b587a41c91b8d0d7" # 6.4.1

if [ ! -d "$SRC_DIR" ]; then
  mkdir $SRC_DIR
fi

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

git clone $REPOLOC
cd $CODE_DIR
git checkout $REVISION

cd $CODE_DIR

./configure --libdir=$LIB_DIR  --enable-gpl --enable-linsys --swig-languages=python
make
