#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR=$SCRIPT_DIR"/build"
LIB_DIR=$BUILD_DIR"/lib"
INCLUDE_DIR=$BUILD_DIR"/include"
SRC_DIR=$SCRIPT_DIR"/src"
CODE_DIR=$SRC_DIR"/x264"

REPOLOC="git://repo.or.cz/x264.git"
REVISION="HEAD"

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

git clone $REPOLOC
cd $CODE_DIR
git checkout $REVISION

export CFLAGS="-I$INCLUDE_DIR"
export LDFLAGS="-L$LIB_DIR"
export PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig:$PKG_CONFIG_PATH"

./configure --prefix=$BUILD_DIR --disable-lavf --disable-ffms --disable-gpac --disable-swscale --enable-shared
make
make install
