#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SRC_DIR=$SCRIPT_DIR"/src"
CODE_DIR=$SRC_DIR"/x264"

LIB_DIR="/usr/lib/x86_64-linux-gnu"

REPOLOC="git://repo.or.cz/x264.git"
REVISION="HEAD"

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

git clone $REPOLOC
cd $CODE_DIR
git checkout $REVISION

cd $CODE_DIR

./configure --libdir=$LIB_DIRR --disable-lavf --disable-ffms --disable-gpac --disable-swscale --enable-shared
make
