#!/bin/bash

CODE_DIR=$SRC_DIR"/lame-RELEASE__3_99_5"

REPOLOC="https://github.com/rbrito/lame/archive/RELEASE__3_99_5.tar.gz"
REVISION=

if [ ! -d "$SRC_DIR" ]; then
  mkdir $SRC_DIR
fi

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

curl -L $REPOLOC | tar -xz

cd $CODE_DIR

export CFLAGS="-I$INCLUDE_DIR"
export LDFLAGS="-L$LIB_DIR"

./configure --prefix=$FINAL_INSTALL_DIR --libdir=$FINAL_INSTALL_DIR --disable-decoder --disable-frontend
make
make install
