#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR=$SCRIPT_DIR"/build"
LIB_DIR=$BUILD_DIR"/lib"
INCLUDE_DIR=$BUILD_DIR"/include"
SRC_DIR=$SCRIPT_DIR"/src"
CODE_DIR=$SRC_DIR"/lame-RELEASE__3_99_5"

REPOLOC="https://github.com/rbrito/lame/archive/RELEASE__3_99_5.tar.gz"
REVISION=

if [ ! -d "$SRC_DIR" ]; then
  mkdir $SRC_DIR
fi

if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

curl -L $REPOLOC | tar -xz

cd $CODE_DIR

export CFLAGS="-I$INCLUDE_DIR"
export LDFLAGS="-L$LIB_DIR"
export PKG_CONFIG_PATH="$BUILD_DIR/lib/pkgconfig:$PKG_CONFIG_PATH"

./configure --prefix=$BUILD_DIR --libdir=$BUILD_DIR/lib --disable-decoder --disable-frontend
make
make install
