#!/bin/bash

CODE_DIR=$SRC_DIR"/frei0r"

REPOLOC="git://github.com/dyne/frei0r.git"
REVISION="HEAD"


if [ -d "$CODE_DIR" ]; then
  echo "Deleting dir "$CODE_DIR
  rm -rf $CODE_DIR 
  mkdir $CODE_DIR
fi

cd $SRC_DIR

git clone $REPOLOC
cd $CODE_DIR
git checkout $REVISION

export CFLAGS="-I$INCLUDE_DIR"
export LDFLAGS="-L$LIB_DIR"

autoreconf -i
./configure --prefix=$FREIOR_DIR --libdir=$FREIOR_DIR
make
make install
