#!/bin/bash

# Make sure were in script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

# Compile libs
#$DIR/compile-libs


# Recipe is available from appimage people, get it, run it.
########   Recipe is broken, but earlier version works wget "https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe"
bash -ex Recipe Flowblade


# Binaries are installed in 
LIBS_SOURCE_DIR=$DIR"/build/lib"


# Copy libs and mlt.py and_mlt.so
./libcopy $LIBS_SOURCE_DIR > l1
./mltpycopy $DIR"/src" > l2
./libfixlinks $LIBS_SOURCE_DIR $DIR > l3


# Build AppImage
cd $DIR
cd Flowblade 
./appimagetool ./Flowblade.AppDir


echo "AppImage created with new binaries."


# Go back script dir
cd ..

