#!/bin/bash

SOURCE_DIR_ROOT=$1
DEST_DIR_ROOT=$2

SOURCE_LIB_DIR=$SOURCE_DIR_ROOT"/lib"
DEST_LIB_DIR=$DEST_DIR_ROOT"/Flowblade/Flowblade.AppDir/usr/lib/x86_64-linux-gnu"


#echo $SOURCE_DIR_ROOT
#echo $DEST_DIR_ROOT
echo $DEST_LIB_DIR

cd $DEST_LIB_DIR

# libmlt, fix link
ln -s -f libmlt.so.6.4.1 libmlt.so.6


# libavutil, delete old, copy new, link
rm $DEST_LIB_DIR"/libavutil.so.52"
cp $SOURCE_LIB_DIR"/libavutil.so.55" $DEST_LIB_DIR"/libavutil.so.55"
ln -s -f libavutil.so.55.47.100 libavutil.so.55

# libswscale, delete old, copy new, link
rm $DEST_LIB_DIR"/libswscale.so.2"
cp $SOURCE_LIB_DIR"/libswscale.so.4" $DEST_LIB_DIR"/libswscale.so.4"
ln -s -f libswscale.so.4.3.101 libswscale.so.4


# libavdevice, delete old
rm $DEST_LIB_DIR"/libavdevice.so.53"


# libpng12, delete broken
rm $DEST_LIB_DIR"/libpng12.so.0"



#$ ln -s -f .profile test
#$ ls -al test
#lrwxrwxrwx 1 pascal pascal 8 2009-09-23 17:12 test -> .profile

#./Flowblade/Flowblade.AppDir/usr/lib/x86_64-linux-gnu/libmlt.so.6
#./Flowblade/Flowblade.AppDir/usr/lib/x86_64-linux-gnu/libavutil.so.52
#./Flowblade/Flowblade.AppDir/usr/lib/x86_64-linux-gnu/libswscale.so.2
#./Flowblade/Flowblade.AppDir/usr/lib/x86_64-linux-gnu/libavdevice.so.53
#./Flowblade/Flowblade.AppDir/usr/lib/x86_64-linux-gnu/libpng12.so.0
