#!/usr/bin/python

import os
import sys
import fnmatch
import shutil


# Get dirs
SOURCE_ROOT_DIR = sys.argv[1]
APPIMAGE_NAME = "Flowblade"
DEST_ROOT_DIR = os.path.dirname(os.path.abspath(sys.argv[0])) + "/" + APPIMAGE_NAME + "/" + APPIMAGE_NAME + ".AppDir"

# Returns filename->path dict of files matching pattern
def get_file(root_folder, pattern):
    last_found = None
    count = 0
    for root, dirnames, filenames in os.walk(root_folder):

        for filename in fnmatch.filter(filenames, pattern):
            path = os.path.join(root, filename)
            last_found = path
            count += 1

    print str(count)," found for pattern ", pattern
    return last_found

def copy_file(file_name):
    source_path = get_file(SOURCE_ROOT_DIR, file_name)
    dest_path = get_file(DEST_ROOT_DIR, file_name)
    print "COPY: ", source_path, " -> ", dest_path
    shutil.copyfile(source_path, dest_path)
    
    
copy_file("mlt.py")
copy_file( "_mlt.so")

"""
print get_file(SOURCE_ROOT_DIR, "mlt.py")
print get_file(SOURCE_ROOT_DIR, "mlt.pyc")
print get_file(SOURCE_ROOT_DIR, "_mlt.so")
print get_file(DEST_ROOT_DIR, "mlt.py")
print get_file(DEST_ROOT_DIR, "mlt.pyc")
print get_file(DEST_ROOT_DIR, "_mlt.so")
"""
