#!/bin/bash

CODE_SOURCE_DIR="/home/janne/codes/flowblade"
WORK_DIR="/home/janne/codes/debs/PACKAGING/deb_packing/tarbuild"
APP_ROOT="/flowblade/flowblade/flowblade-trunk"
VERSION="1.4.0"
PACKAGE_NAME="flowblade-"$VERSION
DIST_TAR=$PACKAGE_NAME".tar.gz"

# LOOK OUT!!!!!!!
# Delete and recreate workdir
rm -rf $WORK_DIR
mkdir $WORK_DIR

# Copy application source and resource files
cp -r $CODE_SOURCE_DIR $WORK_DIR

# Use distutils to create a tar archive
cd $WORK_DIR$APP_ROOT
./setup.py sdist

